### PR TITLE
Encode objects within arrays to include indices

### LINKED ISSUE #11: Allow objects to be encoded to include indices
Given the following object:

```js
{items: [{name:'one'}, {name:'two'}]}
```

can-param will encode this as:

```
items[][name]=one&items[][name]=two
```

Express.js' body parser will parse this as:

```
{"items":[{"name":["one","two"]}]}
```

Which is incorrect. If the arrays included indices like so:

```
items[0][name]=one&items[1][name]=two
```

Then it would be correctly encoded as separate objects.  We should provide an option for doing this.

### PR DESCRIPTION
**Pull request by matthewp**
This makes it so that objects within arrays include the index.

```
{items: [{name:'one'}, {name:'two'}]}
```

becomes

```
items[0][name]=one&items[1][name]=two
``

Note that non-objects will not include the index. This is to match
jQuery's encoder.

```
{items: [{name:'one'}, {name:'two'}]}
```

Still becomes

```
items[]=one&items[]=two
```

Fixes #11

### CODE REVIEW

File: can-param.js [hunk 1]
```diff
@@ -4,7 +4,10 @@ var namespace = require("can-namespace");
 function buildParam(prefix, obj, add) {
 	if (Array.isArray(obj)) {
 		for (var i = 0, l = obj.length; i < l; ++i) {
-			buildParam(prefix + '[]', obj[i], add);
+			var inner = obj[i];
+			var shouldIncludeIndex = typeof inner === 'object';
```
Comment (justinbmeyer) [inline can-param.js:8]: what should `null` do?

Comment (matthewp) [reply can-param.js:8]: jQuery includes an index for null.
